spring:
  application:
    name: tasksphere
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tasksphere}
    username: ${DB_USER:tasksphere}
    password: ${DB_PASSWORD:tasksphere}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true

server:
  port: ${PORT:8080}
  forward-headers-strategy: native

security:
  jwt:
    secret: ${JWT_SECRET:change-me-please-long-secret}
    issuer: tasksphere
    expiration-minutes: 60

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,threaddump,heapdump,loggers
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.security: INFO
