server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tasksphere}
    username: ${DB_USER:tasksphere}
    password: ${DB_PASSWORD:tasksphere}
  jpa:
    hibernate:
      ddl-auto: validate   # Flyway manages schema
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: false
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      timeout: 2s

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    level:
      org.springframework.data.redis: DEBUG
      io.lettuce.core: INFO
  pattern:
    console: "%msg%n"  # logstash appender handles JSON

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always

# Logback encoder config is picked from dependency; fine as-is
